### ISSUE TITLE
Незручне редагування

### ISSUE THREAD

**Issue by DenysNosov** [saharin88/com_translator#1]
Якщо редагувати файл то необхідно кожну константу відкривати в модальному вікні.
https://nimb.ws/EroPJh

В com_localise це быльш зручныше зроблено:
https://nimb.ws/pLVbyI

Також незрозуміла логіка:
1. клікаючи на ключ відкривається сорінка для редагування значення
2. біля значення є іконка яка відкриває лайтбокс

**Comment by saharin88** [comment]
Додав режим редагування
![2020-05-04_0039](https://user-images.githubusercontent.com/5886549/81436852-d25f9480-9172-11ea-8db6-0c5d193cae13.png)
