### ISSUE TITLE
Відсутня можливість перекладу по окремому ключу

### ISSUE THREAD

**Issue by DenysNosov** [saharin88/com_translator#2]
Можна перекласти повністю файл, але немає можливості перекласти окрему константу. Це буде не дуже зручно коли є більша частина констант перекладена, а інші неперекладені константи як перекладати?

**Comment by saharin88** [comment]
Можна вибрати потрібні константи, одну чи більше, для перекладу, поставивши галочку біля потрібної констатнти.
