### ISSUE TITLE
Что насчёт обработки *.sys файлов?

### ISSUE THREAD

**Issue by kernusr** [saharin88/com_translator#3]
Компонент не обрабатывает *.sys.ini файлы, однако в них может содержаться достаточно большое количество констант для перевода (например, https://github.com/akeeba/engage/blob/development/component/language/backend/en-GB/en-GB.com_engage.sys.ini)

**Comment by saharin88** [comment]
![зображення](https://user-images.githubusercontent.com/5886549/82072270-1ce79080-96e0-11ea-8988-0e9c89520203.png)
